config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :users, only: [:index, :show]

  resources :rounds, only: [:index, :show, :new, :create, :update] do
    resources :votes, only: [:new, :create]

    get 'finalize', on: :member
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
  has_many :vote

  validates :lie, inclusion: { in: [nil, 1, 2, 3] }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :vote
  has_many :round, :through => :vote

  validates :email, format: { with: /@siftscience.com\z/,
    message: "Sift Science email address required" }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.users_with_vote_counts
    joins(:round).where('rounds.lie IN (1,2,3)').select('users.*')
      .select('SUM(CASE WHEN rounds.lie = votes.statement THEN 1 END) ' +
              ' AS correct_votes')
      .select('SUM(CASE WHEN rounds.lie <> votes.statement THEN 1 END) ' +
              ' AS incorrect_votes')
      .group('users.id')
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :round

  validates :statement, inclusion: { in: [1, 2, 3] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to rounds_path
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    puts current_user
    @rounds = Round.all

    @finished_rounds = @rounds.select { |r| r.lie }.map do |round|
      {
        id: round.id,
        name: round.name,
        created_at: round.created_at,
      }
    end

    @open_rounds = @rounds.reject { |r| r.lie }.map do |round|
      {
        id: round.id,
        name: round.name,
        created_at: round.created_at,
        voted: round.vote.where(:user => @user).present?
      }
    end
    puts @open_rounds
  end

  def show
    @round = Round.find(params[:id])
    @user = current_user

    # If the round is open and this user hasn't voted yet, redirect.
    if @round.lie.nil? and @user.vote.where(:round => @round).first.nil?
      redirect_to new_round_vote_path(@round)
    end

    # Otherwise, show the votes (and the answer, if it has been entered).
    @votes = @round.vote.all.to_a
    @totals = ((1..3).map { |i| [i, @votes.count { |v| v.statement == i }] }).to_h
  end

  def new
    @round = Round.new
  end

  def create
    round_params =
      params.require(:round).permit(:name,:statement1,:statement2,:statement3)
    @round = Round.new(round_params)
    if @round.save
      redirect_to @round
    else
      render 'new'
    end
  end

  def finalize
    @round = Round.find(params[:id])
    if @round.lie
      redirect_to @round
    end
  end

  def update
    @round = Round.find(params[:id])
    if @round.lie
      # TODO(jburnim): Return some kind of warning message and 409 status code?
      redirect_to @round
    end

    @round.lie = params.require(:round).require(:lie)
    if @round.save
      redirect_to @round
    else
      render 'finalize'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.users_with_vote_counts.map do |user|
      correct_votes = user.correct_votes || 0
      incorrect_votes = user.incorrect_votes || 0
      total_votes = correct_votes + incorrect_votes
      {
        id: user.id,
        email: user.email.html_safe,
        correct_votes: correct_votes,
        incorrect_votes: incorrect_votes,
        total_votes: total_votes,
        correct_rate: correct_votes / (total_votes + Float::MIN),
        incorrect_rate: incorrect_votes / (total_votes + Float::MIN)
      }
    end
    @users.sort_by! { |user| -user[:correct_rate] }
  end

  def show
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def new
    @round = Round.find(params[:round_id])

    # If the user has already voted, redirect.
    @user = current_user
    if @user.vote.where(:round => @round).first
      redirect_to round_path(@round)
    end

    @vote = @round.vote.new
  end

  def create
    @user = current_user
    @round = Round.find(params[:round_id])
    @vote = @round.vote.new(vote_params)
    @vote.user = @user
    if @vote.save
      redirect_to @round
    else
      render 'new'
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:statement)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Two Truths and a Lie</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">2T1L</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="<%= rounds_path %>">Games</a></li>
          <li><a href="<%= users_path %>">Leaderboard</a></li>
        </ul>
      </div> <!-- /.navbar-collapse -->
    </div> <!-- /.container-fluid -->
  </nav>

  <% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <%= notice %>
  </div>
  <% end %>

  <% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <%= alert %>
  </div>
  <% end %>

  <div class="container" role="main">
    <%= yield %>
  </div>

</body>
</html>

app/views/rounds/finalize.haml
%h2= 'Finalize Two Truths and Lie Game for ' + @round.name

%p Which statement was the lie?

= form_for [@round], url: {action: 'update'} do |f|
    = f.radio_button :lie, '1'
    = f.label :lie, @round.statement1, :value => '1'
    %br
    = f.radio_button :lie, '2'
    = f.label :lie, @round.statement2, :value => '2'
    %br
    = f.radio_button :lie, '3'
    = f.label :lie, @round.statement3, :value => '3'
    %br
    = f.submit 'Submit'

%p NOTE: Once the lie has been submitted, no further votes will be accepted.

app/views/rounds/index.haml
.page-header
  %h1 Open Games

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Date
      %th
      %th
  %tbody
    - @open_rounds.each do |round|
      %tr
        %td= round[:name]
        %td= round[:created_at]
        %td
          - if round[:voted]
            = link_to('view', round_path(round[:id]))
          - else
            = link_to('finalize', finalize_round_path(round[:id]))
        %td= if !round[:voted] then link_to('vote', round_path(round[:id])) end

%p
  = link_to('New Game', new_round_path)


.page-header
  %h1 Completed Games

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Date
      %th
  %tbody
    - @finished_rounds.each do |round|
      %tr
        %td= round[:name]
        %td= round[:created_at]
        %td= link_to('view', round_path(round[:id]))

app/views/rounds/new.haml
%h2 Creating a new round.

= form_for @round, url: {action: 'create'} do |f|
  = f.label(:name, 'Name:')
  = f.text_field :name
  %br
  %br
  = f.label :statement1, 'First statement:'
  %br
  = f.text_area :statement1, size: '70x4'
  %br
  = f.label :statement2, 'Second statement:'
  %br
  = f.text_area :statement2, size: '70x4'
  %br
  = f.label :statement3, 'Third statement:'
  %br
  = f.text_area :statement3, size: '70x4'
  %br
  = f.submit 'Create'

app/views/rounds/show.haml
.page-header
  %h1 Two Truths and a Lie

%p= @round.name
%p{:style => (@round.lie == 1) ? 'font-weight: bold' : ''}
  = '(' + pluralize(@totals[1], 'vote') + ')'
  = @round.statement1.html_safe
%p{:style => (@round.lie == 2) ? 'font-weight: bold' : ''}
  = '(' + pluralize(@totals[2], 'vote') + ')'
  = @round.statement2.html_safe
%p{:style => (@round.lie == 3) ? 'font-weight: bold' : ''}
  = '(' + pluralize(@totals[3], 'vote') + ')'
  = @round.statement3.html_safe


- if @round.lie.nil?
  %p
    = link_to('Finalize this Game', finalize_round_path(@round))


%h2 Votes

%table.table.table-striped
  %thead
    %tr
      %th User
      %th Vote
  %tbody
    - @votes.each do |vote|
      %tr
        %td= vote.user.email
        %td= 'Statement ' + vote.statement.to_s

app/views/users/index.haml
.page-header
  %h1 Leaderboard

%table.table.table-striped
  %thead
    %tr
      %th User
      %th Correct
      %th Incorrect
      %th Accuracy
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to(user[:email], user_path(user[:id]))
        %td= user[:correct_votes]
        %td= user[:incorrect_votes]
        %td= user[:correct_rate]

app/views/users/show.haml
TODO(jburnim): Show all votes by this user.

app/views/votes/new.haml
%p= @round.name.html_safe

= form_for [@round, @vote], url: {action: 'create'} do |f|
    = f.radio_button :statement, '1'
    = f.label :statement, @round.statement1.html_safe, :value => '1'
    %br
    = f.radio_button :statement, '2'
    = f.label :statement, @round.statement2.html_safe, :value => '2'
    %br
    = f.radio_button :statement, '3'
    = f.label :statement, @round.statement3.html_safe, :value => '3'
    %br
    = f.submit 'Vote'